### ISSUE TITLE
Token contract does not reject overspending from user account, and does not increase token supply

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-stable-coin#3]
I submitted $1000 in stablecoin from a user who only had a balance of $230. The transaction was successful and reflected as such on both the user UI and admin UI. Token supply did not increase. The receiving account balance did not update.

Could either be in the UI or in the contract but needs to be resolved.

![Screen Shot 2020-10-07 at 11 38 39 AM](https://user-images.githubusercontent.com/42808726/95355923-18d92c80-0894-11eb-8cee-9e4f1cadea0b.png)
![Screen Shot 2020-10-07 at 11 38 32 AM](https://user-images.githubusercontent.com/42808726/95355924-1971c300-0894-11eb-97cb-721a78eb4320.png)

**Comment by jeanniesarah** [comment]
Any resolutions?

**Comment by donaldthibeau** [comment]
Issue is in the UI vs. contract side.
